# Generated by Django 2.2 on 2020-03-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHobbies', '0002_auto_20200330_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online_hobbies',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='online_hobbies',
            name='updated_date',
        ),
    ]
