# Generated by Django 2.2 on 2020-03-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHobbies', '0003_auto_20200330_0252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Online_Hobbies',
            new_name='OnlineHobbies',
        ),
    ]
