# Generated by Django 2.2 on 2020-03-30 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHobbies', '0004_auto_20200330_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinehobbies',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
