# Generated by Django 2.2 on 2020-04-01 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHobbies', '0005_onlinehobbies_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinehobbies',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='onlinehobbies',
            name='get_started',
        ),
        migrations.AddField(
            model_name='onlinehobbies',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
