# Generated by Django 2.2 on 2020-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHobbies', '0006_auto_20200331_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinehobbies',
            name='image',
            field=models.ImageField(upload_to='User/images'),
        ),
    ]
