# Generated by Django 2.2 on 2020-04-10 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineHobbies', '0007_auto_20200401_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassVideoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=100)),
                ('class_subtitle', models.CharField(max_length=100)),
                ('class_requirements', models.TextField(max_length=2500)),
                ('class_goal', models.TextField(max_length=2500)),
                ('class_video_links', models.CharField(max_length=25)),
                ('online_hobby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OnlineClassVideoPage', to='OnlineHobbies.OnlineHobbies')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClassEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('online_hobby_name', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='OnlineClassEnroll', to='OnlineHobbies.OnlineHobbies')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
